import type { Metadata } from "next";
import "./globals.css";
import { MenuList } from "@/components/shared/menu-list";
import { MenuSearch } from "@/components/shared/menu-search";



export const metadata: Metadata = {
  title: "SunnyGaze",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MenuList></MenuList>
        <MenuSearch></MenuSearch>
        {children}
      </body>
    </html>
  );
}
